CREATE TABLE [dbo].[BND]
(
	[BNDID] INT NOT NULL PRIMARY KEY IDENTITY, 
 
    [ChildName] VARCHAR(100) NULL, 
    [Gender] VARCHAR(50) NULL, 
    [DateOfBirth] DATE NULL, 
    [TDate] DATE NULL, 
    [PlaceOfBirth] VARCHAR(50) NULL, 
	[PlaceOfBirthHouse] VARCHAR(50) NULL, 

    [NameOfMother] VARCHAR(100) NULL, 
    [UIDmother] INT NULL, 
    [NameOfFather] VARCHAR(100) NULL, 
    [UIDfather] INT NULL, 
    [GrandFather] VARCHAR(100) NULL, 
    [GrandMother] VARCHAR(100) NULL, 
    [AddressParentsBirth] VARCHAR(250) NULL, 
    [PermAddress] VARCHAR(250) NULL, 
    [InformantsName] VARCHAR(100) NULL, 
    [InformantAddress] VARCHAR(250) NULL, 
    [NameOfTown] VARCHAR(100) NULL, 
    [TownOrVillage] BIT NULL, 
    [NameOfDistrict] VARCHAR(100) NULL, 
    [NameOfState] VARCHAR(100) NULL, 
    [ReligionOfFamily] VARCHAR(50) NULL, 
    [AnyOtherReligion] VARCHAR(50) NULL, 
    [FEduc] VARCHAR(50) NULL, 
    [MEduc] VARCHAR(50) NULL, 
    [FOccup] VARCHAR(50) NULL, 
    [MOccup] VARCHAR(50) NULL, 
    [AgeOfMotherMarraige] INT NULL, 
    [AgeOfMotherBirth] INT NULL, 
    [NoOfChild] INT NULL, 
    [AttentionType] VARCHAR(100) NULL, 
    [DeliveryMethod] VARCHAR(100) NULL, 
    [BirthWeight] INT NULL, 
    [DurationOfPregnancy] VARCHAR(50) NULL,
	
	[UserID] NVARCHAR(128) NUll,
    [WEBstatusID] INT NULL, 
    [RegisterTypeID] INT NULL, 
    CONSTRAINT [FK_Birth_RegisterType] FOREIGN KEY ([RegisterTypeID]) REFERENCES [RegisterTypes]([RegisterTypeID]), 
    CONSTRAINT [FK_Birth_WEBstatus] FOREIGN KEY ([WEBstatusID]) REFERENCES [WEBstatus]([WEBstatusID]), 
    CONSTRAINT [FK_Birth_AspNetUsers] FOREIGN KEY ([UserID]) REFERENCES [AspNetUsers]([Id])
)
