SET IDENTITY_INSERT [dbo].[SubLedgers] ON
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (2, 4, 1, N'House Tax', 1)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (3, 2, 3, N'V.P Member Salaries', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (4, 1, 3, N'Matching Grants', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (5, 3, 3, N'Transfer of assets grants from C.C.P', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (6, 3, 3, N'MNREGS Grants', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (7, 3, 3, N'Govt. Grant For Garbage', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (8, 3, 3, N'XIV Finance', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (9, 3, 3, N'Deendayal Grants', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (10, 4, 1, N'Professional Tax', 1)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (11, 4, 1, N'Sign Board Tax', 1)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (12, 4, 1, N'Garbage Tax', 1)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (13, 4, 2, N'Const. Lic Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (14, 4, 2, N'Sanitation Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (15, 4, 2, N'Minor Repair Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (16, 4, 2, N'Certificate Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (17, 4, 2, N'House Tax Transfer Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (18, 4, 2, N'Reg. Of Unit Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (19, 4, 2, N'R.B.D Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (20, 4, 2, N'Market Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (21, 4, 2, N'Other Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (22, 6, 3, N'Sale Of Tender Form', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (23, 6, 3, N'Sale Of Old Items', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (24, 6, 3, N'Others', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (25, 7, 3, N'E.M.D Deposit', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (26, 7, 3, N'Security Deposit', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (27, 7, 3, N'Income Tax', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (28, 7, 3, N'Royalty', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (29, 7, 3, N'VAT', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (30, 7, 3, N'V.P Shop Rent', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (31, 7, 3, N'Community Hall Charges', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (32, 7, 3, N'Comunity Hall SD', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (33, 7, 3, N'Bank Interest', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (34, 7, 3, N'Fine', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (35, 7, 3, N'Recovery Of Damages To Hall', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (36, 7, 3, N'Public Contribution', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (37, 7, 3, N'Recovery Reciepts', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (38, 7, 3, N'Contribution to P.F fund', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (39, 7, 3, N'Other Reciepts', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (40, 8, 3, N'Staff / Daily wages clerk Salaries', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (41, 8, 3, N'Elected Member Salaries', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (42, 8, 3, N'Stationary', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (43, 8, 3, N'Printings', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (44, 8, 3, N'Office Light Bill', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (45, 8, 3, N'Water Bill', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (46, 8, 3, N'Telephone Bill', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (47, 8, 3, N'Revenue and Postage', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (48, 8, 2, N'Xerox', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (49, 8, 3, N'Xerox Machine Maintenance', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (50, 8, 3, N'Office Maintenannce', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (51, 8, 3, N'Maintenance of Computer', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (52, 8, 3, N'Refreshment', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (53, 8, 3, N'Others/Data of Records', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (54, 8, 3, N'Advocate Fees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (55, 8, 3, N'Chartered Accountant Fee', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (56, 8, 3, N'T.A.D.A', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (57, 9, 3, N'Disposal of Garbage(house to house) ', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (58, 9, 3, N'Purchase of Garbage Bins', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (59, 9, 3, N'Disposal of Stray Cattle & Dogs Sterilization.', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (60, 9, 3, N'Disposal of Dead bodies of animals', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (61, 9, 3, N'Construction Of garbage pits/shed', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (62, 9, 3, N'Segregation plastic at site/Bailing machine', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (63, 9, 3, N'Daily wages Labourers at site', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (64, 9, 3, N'J.C.B at garbage', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (65, 9, 3, N'Erection of Locked shed for Garbage', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (66, 9, 3, N'Transportation, lifting, disposal of garbage', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (67, 9, 3, N'Garbage Treatment Plant', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (68, 9, 3, N'Development at garbage site with ', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (69, 10, 3, N'Const. of Drain, Culvert Roads Retaining wall', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (70, 10, 3, N'laying pavers/R.C.C slabs', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (71, 10, 3, N'Development of open spaces cum gardens', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (72, 10, 3, N'Purchase of electrical goods', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (73, 10, 3, N'Cutting of uprooted trees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (74, 10, 3, N'Cutting of roadside bushes & trees', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (75, 10, 3, N'Cleaning of rain water drains', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (76, 10, 3, N'Up keeping of gardens', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (77, 10, 3, N'R.D.A works', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (78, 10, 3, N'Petrol for grass cutters', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (79, 10, 3, N'Daily wages for grass cutting machine', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (80, 10, 3, N'Painting of V.P Gardens/Retaining walls', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (81, 10, 1, N'V.P Gardens Maintenance / Water', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (82, 10, 3, N'Purchase of garden equipments', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (83, 10, 3, N'Removal of roadside derbies.', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (84, 10, 3, N'Minor Works', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (85, 10, 3, N'Extension of Street light lines with poles', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (86, 10, 3, N'Maintenance of jeep vehicle and truck', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (87, 10, 3, N'Maintenance of community hall', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (88, 10, 3, N'Other/ Construction of soak pits', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (89, 10, 3, N'Cleaning of public places', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (90, 10, 3, N'Hire of JCB machines', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (91, 10, 3, N'Daily wages payment for jeep and truck driver', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (92, 10, 3, N'Deendayal Works', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (93, 10, 3, N'Hall electric Bill', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (94, 10, 3, N'Hall cleaning', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (95, 10, 3, N'Hall/Supervision/Electricity/A/c', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (96, 10, 3, N'Hall A/c repair/Maintenance', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (97, 10, 3, N'Hall Furnishing/Chairs/Security at Garbge site', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (98, 10, 3, N'Market Repair', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (99, 10, 3, N'Development works under XIV Finance grants', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (100, 12, 3, N'Financial help for funeral expenses', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (101, 12, 3, N'Natural Calamities', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (102, 12, 3, N'Balwadi Rent', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (103, 12, 3, N'Financial assistant for poor students', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (104, 12, 3, N'Agricultural Scheme', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (105, 12, 3, N'Others', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (106, 13, 3, N'National Days', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (107, 13, 3, N'Sports', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (108, 13, 3, N'Contribution to exibhition in the village', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (109, 13, 3, N'Books for poor students', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (110, 13, 3, N'School Uniforms', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (111, 13, 3, N'Others', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (112, 13, 3, N'Cleaning and maintenance of drinking water wells', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (113, 16, 3, N'Newspaper,Books', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (114, 17, 3, N'Construction of Toilets', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (115, 17, 3, N'Maintenance of Sulabh Toilets', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (116, 17, 3, N'Cleaning of sewage drains', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (117, 17, 3, N'Daily wages labourers for malaria prevention', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (119, 17, 3, N'Others', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (120, 19, 3, N'Refund of E.M.D  of Works', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (121, 19, 3, N'Refund of security deposits of work', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (122, 19, 3, N'Payment of Income Tax', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (123, 19, 3, N'Payment of VAT Tax', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (124, 19, 3, N'Payment of Royalty', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (125, 19, 3, N'Payment of Luxury Tax', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (126, 19, 3, N'Advertisments', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (127, 19, 3, N'Refund of S.D. of hall', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (128, 19, 3, N'Service Tax', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (129, 19, 3, N'Other Misc', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (130, 4, 2, N'Income Certificate', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (131, 4, 2, N'Divergence Certificate ', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (132, 4, 2, N'Residence Certificate', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (133, 4, 2, N'Issue BND Certificate', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (134, 4, 2, N'Right To Information', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (135, 19, 3, N'GST', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (137, 8, 3, N'Stamp', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (138, 8, 3, N'DeadStock', 0)
INSERT INTO [dbo].[SubLedgers] ([SubLedgerID], [LedgerID], [SubLedgerTypeID], [Ledger], [HasDemand]) VALUES (139, 8, 3, N'Street Light Articles', 0)
SET IDENTITY_INSERT [dbo].[SubLedgers] OFF
