SET IDENTITY_INSERT [dbo].[Ledgers] ON
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (1, N'GENERAL', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (2, N'GRANTS FROM GOVERMENT', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (3, N'OTHER GRANTS', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (4, N'TAXES AND FEES', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (5, N'PROCEED OF LOANS', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (6, N'SALE PROCEEDS', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (7, N'EXTRAORDINARY REPORTS', 1)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (8, N'ADMINISTRATION', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (9, N'SANITATION AND PUBLIC HEALTH AND FAMILY WELFARE', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (10, N'PUBLIC WORKS', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (11, N'PLANNING AND DEVELOPMENT', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (12, N'SOCIAL WELFARE', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (13, N'EDUCATION AND CULTURE', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (14, N'RURAL HOUSING', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (15, N'DRINKING WATER', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (16, N'LIBRARIES', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (17, N'PUBLIC SANITATION', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (18, N'CONSTRUCTION AND MAINTENANCE  OF SLAUGHTE HOUSE', 0)
INSERT INTO [dbo].[Ledgers] ([LedgerID], [Ledger], [IsIncome]) VALUES (19, N'MISCELLENOUS', 0)
SET IDENTITY_INSERT [dbo].[Ledgers] OFF
